### ISSUE TITLE
Santa extension fail to build 

### ISSUE THREAD

**Issue by AndersTao** [trailofbits/osquery-extensions#18]
Hi , and thanks for sharing the extension

I have been able to build the `efigy` extension with no problems, but when I try with the Santa extension, it fails with this output: https://gist.github.com/AndersTao/650518ee32d5df58118f70b8eb71677b

Shout I setup a vm with 10.12 to do the build, or maybe I am missing something else?

**Comment by alessandrogario** [comment]
We have finished updating the repository, while also adding extension bundling and providing the first release. Please try again to build the extension (or use the provided binary packages).
