### ISSUE TITLE
fwctl build errors when built with osquery 3.2.9

### ISSUE THREAD

**Issue by mike-myers-tob** [trailofbits/osquery-extensions#24]
**osquery version:** 3.2.9-98-g2f872cb9
**Name and version of OS tested on:** Windows 10

The final build step (building the extensions) fails, with the following errors related to `safeStrtoull`:

```
C:\Projects\osquery-fb-master\external\extension_trailofbits\fwctl\src\portblacklist.cpp(506): error C2039: 'safeStrtoull': is not a member of 'osquery' [C:\Projects\osquery-fb-master\build
\windows10\external\trailofbits_osquery_extensions.vcxproj]
C:\Projects\osquery-fb-master\external\extension_trailofbits\fwctl\src\portblacklist.cpp(506): error C3861: 'safeStrtoull': identifier not found [C:\Projects\osquery-fb-master\build\windows
10\external\trailofbits_osquery_extensions.vcxproj]
```

This function was apparently removed from osquery after 3.2.6 or so.

Replace it with `tryTo<'unsigned long long'>` ?

**Comment by mike-myers-tob** [comment]
Office hours today: confirmed that they are moving away from `safeStrtoull` toward `tryTo`

**Comment by GarretReece** [comment]
Fixed with commit https://github.com/trailofbits/osquery-extensions/commit/f369aad742e199577abd651318243ac1ccad214f
