### ISSUE TITLE
Expose the custommsg column in the santa_rules table

### ISSUE THREAD

**Issue by clong** [trailofbits/osquery-extensions#29]
The sqlite schema for the santa.db file is:
```
$ sudo sqlite3 rules.db
sqlite> .schema rules
CREATE TABLE IF NOT EXISTS 'rules' ('shasum' TEXT NOT NULL, 'state' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'custommsg' TEXT);
```
However, the santa_rules table in osquery does not have support for the `custommsg` column:
```
osquery> .schema santa_rules
CREATE TABLE santa_rules(`shasum` TEXT, `state` TEXT, `type` TEXT);
```

We utilize that column to give people more information about why a particular binary is being blocked, so it's very important that we have the ability to INSERT values into that column now that writable tables exist

**Comment by mike-myers-tob** [comment]
@clong I hope you get a chance to try it out, and let us know what you think!

**Comment by clong** [comment]
@mike-myers-tob will test it out this week!
