### ISSUE TITLE
build fails on MacOS

### ISSUE THREAD

**Issue by GarretReece** [trailofbits/osquery-extensions#52]
Building on MacOS fails (even using the 4.0.1 porting branch) with the error `ld: library not found for -lboost_iostreams-mt` at the linking stage of building the extension binary.

**Comment by Smjert** [comment]
@GarretReece this should be fixed now; if you want to verify please use the latest version of the extension port PR and in the osquery repo please use this PR: https://github.com/osquery/osquery/pull/6199

**Comment by mike-myers-tob** [comment]
Should be fixed with the merge of #51
