### ISSUE TITLE
4.0.1 build on windows is not compiling correctly

### ISSUE THREAD

**Issue by teamdome** [trailofbits/osquery-extensions#54]
The build instructions that are written in the README are not working properly as i have followed every step and even though the osqueryi.exe and osqueryd.exe are compiled correctly the extension's exe file isn't created at all and it doesn't even throw a single error, the build instruction for the 3.3.2 sdk were working fine and i was able to compile the extension.

**Comment by mike-myers-tob** [comment]
Should be fixed with the merge of #51
