### ISSUE TITLE
Bundle all plugins into one Trail of Bits extension

### ISSUE THREAD

**Issue by marpaia** [trailofbits/osquery-extensions#6]
If Trail of Bits adds more extensions to this repository, I would love the ability to bundle all plugins provided by each extension into a single extension binary. The ability to combine *specific* plugins into an extension (ie: I want efigy, and foo, but not bar) would be neat, but not required.

The reason why I want this is because I want to distribute the Trail of Bits extension in [Launcher](https://github.com/kolide/launcher), but I don't want to have to package, sign, distribute, and autoupdate each extension that gets added if I can just distribute a single extension that bundles all of the plugins.

**Comment by alessandrogario** [comment]
The following PR adds the required CMake code to make this possible: https://github.com/facebook/osquery/pull/4335

**Comment by mike-myers-tob** [comment]
PR has been merged
