### ISSUE TITLE
mutex registration

### ISSUE THREAD

**Issue by dguido** [trailofbits/osquery-extensions#8]
Provide osquery a list of Windows mutexes and have it register them to block other processes with the same mutex from executing.

https://net.cs.uni-bonn.de/fileadmin/user_upload/wichmann/Infection_Markers_as_Vaccine_against_Malware.pdf

**Comment by scottlundgren** [comment]
@dguido thanks for linking this.  This is an interesting approach.

**Comment by mike-myers-tob** [comment]
Addressed in https://github.com/trailofbits/osquery-extensions/pull/27
